import type { Branch } from './Branch';
import type { Company } from './Company';
import type { Product } from './Product';
import type { ProductUnit } from './ProductUnit';
import type { PurchaseOrderReceiptItem } from './PurchaseOrderReceiptItem';
import type { PurchaseReturn } from './PurchaseReturn';
import type { PurchaseReturnItemSerial } from './PurchaseReturnItemSerial';
import type { VatProfile } from './VatProfile';

export interface PurchaseReturnItem {
  id: string;
  ulid: string;
  company?: Company;
  branch?: Branch;
  purchase_return?: PurchaseReturn;
  purchase_order_receipt_item?: PurchaseOrderReceiptItem | null;
  qty: number;
  product_unit?: ProductUnit | null;
  product?: Product | null;
  product_unit_conversion_value: number;
  product_unit_qty_base: number;
  product_unit_price: number;
  product_unit_is_price_include_vat: boolean;
  price_discount: number;
  price_after_discount: number;
  subtotal: number;
  subtotal_discount: number;
  subtotal_after_discount: number;
  global_discount: number;
  subtotal_after_global_discount: number;
  vat_profile?: VatProfile | null;
  vat_rate: number;
  vat_base_numerator: number;
  vat_base_denominator: number;
  vat_base: number;
  vat: number;
  subtotal_after_vat: number;
  rounding: number;
  amount_payable: number;
  cogs: number;
  total_cogs: number;
  base_unit_cogs: number;
  remarks: string | null;
  serials?: PurchaseReturnItemSerial[];
}
