import type { Branch } from './Branch';
import type { Company } from './Company';
import type { PurchaseAdditionalCost } from './PurchaseAdditionalCost';
import type { PurchaseGlobalDiscount } from './PurchaseGlobalDiscount';
import type { PurchaseItem } from './PurchaseItem';
import type { PurchaseOrder } from './PurchaseOrder';
import type { PurchaseReceipt } from './PurchaseReceipt';
import type { Supplier } from './Supplier';

export interface Purchase {
  id: string;
  ulid: string;
  company?: Company;
  branch?: Branch;
  code: string;
  date: string;
  due_days: number;
  supplier?: Supplier | null;
  purchase_order?: PurchaseOrder | null;
  receipt_mode?: string | null;
  tax_invoice_number?: string | null;
  tax_invoice_vat_base?: string | null;
  tax_invoice_vat?: string | null;
  remarks?: string | null;
  is_posted: boolean;
  item_total_before_global_discount?: string | null;
  global_discount?: string | null;
  item_total_after_global_discount?: string | null;
  vat_base?: string | null;
  vat?: string | null;
  item_total_after_vat?: string | null;
  additional_cost?: string | null;
  rounding?: string | null;
  amount_payable?: string | null;
  amount_paid_by_purchase_order_down_payment?: string | null;
  amount_paid_by_purchase_return?: string | null;
  amount_paid_total?: string | null;
  amount_due?: string | null;
  is_paid_off: boolean;
  progress_status?: string | null;
  item_total_count: number;
  item_matched_count: number;
  item_less_count: number;
  item_more_count: number;
  item_unlinked_count: number;
  items?: PurchaseItem[];
  direct_receipt?: PurchaseReceipt | null;
  manual_receipts?: PurchaseReceipt[];
  global_discounts?: PurchaseGlobalDiscount[];
  additional_costs?: PurchaseAdditionalCost[];
}
