FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    curl \
    git \
    zip \
    unzip \
    ca-certificates \
    apache2 \
    php8.3 \
    php8.3-cli \
    php8.3-curl \
    php8.3-mysql \
    php8.3-opcache \
    php8.3-zip \
    php8.3-intl \
    php8.3-common \
    php8.3-gd \
    php8.3-gmp \
    libapache2-mod-php8.3

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

RUN sed -i 's|/var/www/html|/var/www/html/public|g' /etc/apache2/sites-available/000-default.conf
RUN a2enmod rewrite

WORKDIR /var/www/html

EXPOSE 80

CMD ["apachectl", "-D", "FOREGROUND"]
