FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

# 1. Install System Dependencies & PHP 8.3
RUN apt-get update && apt-get install -y \
    curl \
    git \
    zip \
    unzip \
    ca-certificates \
    apache2 \
    php8.3 \
    php8.3-cli \
    php8.3-curl \
    php8.3-mysql \
    php8.3-opcache \
    php8.3-zip \
    php8.3-intl \
    php8.3-common \
    php8.3-gd \
    php8.3-gmp \
    php8.3-xml \
    php8.3-mbstring \
    php8.3-sqlite3 \
    php8.3-redis \
    php8.3-xdebug \
    libapache2-mod-php8.3 \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# 2. Install Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# 3. Configure Apache
# Set document root to the Laravel public folder
RUN sed -i 's|/var/www/html|/var/www/html/public|g' /etc/apache2/sites-available/000-default.conf
RUN a2enmod rewrite

# 4. Identity Swap: Align www-data with your host user (UID 1000)
# We remove the default 'ubuntu' user to free up ID 1000, 
# then assign it to www-data and give it a login shell (bash).
RUN touch /var/mail/ubuntu && chown root:mail /var/mail/ubuntu && \
    userdel -f ubuntu && \
    if getent group ubuntu; then groupdel ubuntu; fi && \
    usermod -u 1000 -s /bin/bash www-data && \
    groupmod -g 1000 www-data

# 5. Set up the working directory and permissions
# We chown /var/www so VS Code can install its server components
RUN mkdir -p /var/www/html && \
    chown -R www-data:www-data /var/www

# 6. Bake the Xdebug dphp alias permanently into the www-data user profile, for debugging Artisan command
RUN echo "alias dphp='XDEBUG_CONFIG=\"client_host=127.0.0.1\" php -dxdebug.mode=debug -dxdebug.start_with_request=yes'" >> /var/www/.bashrc

WORKDIR /var/www/html

# 6. Final Environment Settings
EXPOSE 80

# Start Apache in the foreground
CMD ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]