export interface ProductFormFieldValues {
    id: string,
    ulid: string,
    company: string,
    code: string,
    product_group: string,
    brand: string,
    name: string,
    product_units: string,
    product_type: string,
    taxable_supply: string,
    standard_rated_supply: number,
    price_include_vat: boolean,
    point: number,
    use_serial_number: boolean,
    has_expiry_date: boolean,
    status: string,
    remarks: string,
}