export interface SupplierFormFieldValues {
    id: string,
    ulid: string,
    company: string,
    code: string,
    name: string,
    contact: string,
    address: string,
    city: string,
    payment_term_type: string,
    payment_term: number,
    taxable_enterprise: number,
    tax_id: string,
    remarks: string,
    status: string,
    supplier_pic: string,
    supplier_products: string,
    selected_products: string,
    main_products: string,
}