<?php

use App\Enums\ChartOfAccountSystemKeyEnum;

return [
    'asset_root' => [
        'system_key' => ChartOfAccountSystemKeyEnum::ASSET_ROOT->value,
        'code' => '10000',
        'name' => 'Aset',
        'account_type' => 'asset',
        'normal_balance' => 'debit',
        'is_group' => true,
        'children' => [
            'current_asset' => [
                'system_key' => ChartOfAccountSystemKeyEnum::ASSET_CURRENT->value,
                'code' => '11000',
                'name' => 'Aset Lancar',
                'account_type' => 'asset',
                'normal_balance' => 'debit',
                'is_group' => true,
                'children' => [
                    'cash_and_cash_equivalents' => [
                        'system_key' => ChartOfAccountSystemKeyEnum::ASSET_CURRENT_CASH_AND_CASH_EQUIVALENTS->value,
                        'code' => '11100',
                        'name' => 'Kas dan Setara Kas',
                        'account_type' => 'asset',
                        'normal_balance' => 'debit',
                        'is_group' => true,
                        'children' => [],
                    ],
                    'account_receivable' => [
                        'system_key' => ChartOfAccountSystemKeyEnum::ASSET_CURRENT_ACCOUNT_RECEIVABLE->value,
                        'code' => '11200',
                        'name' => 'Piutang Usaha',
                        'account_type' => 'asset',
                        'normal_balance' => 'debit',
                        'is_group' => false,
                    ],
                    'inventory' => [
                        'system_key' => ChartOfAccountSystemKeyEnum::ASSET_CURRENT_INVENTORY->value,
                        'code' => '11300',
                        'name' => 'Persediaan',
                        'account_type' => 'asset',
                        'normal_balance' => 'debit',
                        'is_group' => false,
                    ],
                    'prepaid_expense' => [
                        'system_key' => ChartOfAccountSystemKeyEnum::ASSET_CURRENT_PREPAID_EXPENSE->value,
                        'code' => '11400',
                        'name' => 'Biaya Dibayar Dimuka',
                        'account_type' => 'asset',
                        'normal_balance' => 'debit',
                        'is_group' => false,
                    ],
                ],
            ],
            'non_current_asset' => [
                'system_key' => ChartOfAccountSystemKeyEnum::ASSET_NON_CURRENT->value,
                'code' => '12000',
                'name' => 'Aset Tidak Lancar',
                'account_type' => 'asset',
                'normal_balance' => 'debit',
                'is_group' => true,
                'children' => [
                    'fixed_asset' => [
                        'system_key' => ChartOfAccountSystemKeyEnum::ASSET_NON_CURRENT_FIXED_ASSET->value,
                        'code' => '12100',
                        'name' => 'Aset Tetap',
                        'account_type' => 'asset',
                        'normal_balance' => 'debit',
                        'is_group' => false,
                    ],
                    'accumulated_depreciation' => [
                        'system_key' => ChartOfAccountSystemKeyEnum::ASSET_NON_CURRENT_ACCUMULATED_DEPRECIATION->value,
                        'code' => '12200',
                        'name' => 'Akumulasi Penyusutan',
                        'account_type' => 'asset',
                        'normal_balance' => 'credit',
                        'is_group' => false,
                    ],
                    'intangible_asset' => [
                        'system_key' => ChartOfAccountSystemKeyEnum::ASSET_NON_CURRENT_INTANGIBLE_ASSET->value,
                        'code' => '12300',
                        'name' => 'Aset Tidak Berwujud',
                        'account_type' => 'asset',
                        'normal_balance' => 'debit',
                        'is_group' => false,
                    ],
                ],
            ],
        ],
    ],
    'liability_root' => [
        'system_key' => ChartOfAccountSystemKeyEnum::LIABILITY_ROOT->value,
        'code' => '20000',
        'name' => 'Liabilitas',
        'account_type' => 'liability',
        'normal_balance' => 'credit',
        'is_group' => true,
        'children' => [
            'account_payable' => [
                'system_key' => ChartOfAccountSystemKeyEnum::LIABILITY_ACCOUNT_PAYABLE->value,
                'code' => '21000',
                'name' => 'Utang Usaha',
                'account_type' => 'liability',
                'normal_balance' => 'credit',
                'is_group' => false,
            ],
            'tax_payable' => [
                'system_key' => ChartOfAccountSystemKeyEnum::LIABILITY_TAX_PAYABLE->value,
                'code' => '22000',
                'name' => 'Utang Pajak',
                'account_type' => 'liability',
                'normal_balance' => 'credit',
                'is_group' => false,
            ],
        ],
    ],
    'equity_root' => [
        'system_key' => ChartOfAccountSystemKeyEnum::EQUITY_ROOT->value,
        'code' => '30000',
        'name' => 'Ekuitas',
        'account_type' => 'equity',
        'normal_balance' => 'credit',
        'is_group' => true,
        'children' => [
            'retained_earnings' => [
                'system_key' => ChartOfAccountSystemKeyEnum::EQUITY_RETAINED_EARNINGS->value,
                'code' => '32000',
                'name' => 'Laba Ditahan',
                'account_type' => 'equity',
                'normal_balance' => 'credit',
                'is_group' => false,
            ],
        ],
    ],
    'income_root' => [
        'system_key' => ChartOfAccountSystemKeyEnum::INCOME_ROOT->value,
        'code' => '40000',
        'name' => 'Pendapatan',
        'account_type' => 'income',
        'normal_balance' => 'credit',
        'is_group' => true,
        'children' => [
            'sales_income' => [
                'system_key' => ChartOfAccountSystemKeyEnum::INCOME_SALES->value,
                'code' => '41000',
                'name' => 'Pendapatan Penjualan',
                'account_type' => 'income',
                'normal_balance' => 'credit',
                'is_group' => false,
            ],
            'service_income' => [
                'system_key' => ChartOfAccountSystemKeyEnum::INCOME_SERVICE->value,
                'code' => '42000',
                'name' => 'Pendapatan Jasa',
                'account_type' => 'income',
                'normal_balance' => 'credit',
                'is_group' => false,
            ],
        ],
    ],
    'cogs_root' => [
        'system_key' => ChartOfAccountSystemKeyEnum::COGS_ROOT->value,
        'code' => '50000',
        'name' => 'Harga Pokok Penjualan',
        'account_type' => 'expense',
        'normal_balance' => 'debit',
        'is_group' => true,
        'children' => [
            'material_cost' => [
                'system_key' => ChartOfAccountSystemKeyEnum::COGS_MATERIAL_COST->value,
                'code' => '51000',
                'name' => 'Beban Bahan Baku',
                'account_type' => 'expense',
                'normal_balance' => 'debit',
                'is_group' => false,
            ],
            'direct_labor_cost' => [
                'system_key' => ChartOfAccountSystemKeyEnum::COGS_DIRECT_LABOR_COST->value,
                'code' => '52000',
                'name' => 'Beban Tenaga Kerja Langsung',
                'account_type' => 'expense',
                'normal_balance' => 'debit',
                'is_group' => false,
            ],
        ],
    ],
    'expense_root' => [
        'system_key' => ChartOfAccountSystemKeyEnum::EXPENSE_ROOT->value,
        'code' => '60000',
        'name' => 'Beban Operasional',
        'account_type' => 'expense',
        'normal_balance' => 'debit',
        'is_group' => true,
        'children' => [],
    ],
    'other_income_root' => [
        'system_key' => ChartOfAccountSystemKeyEnum::OTHER_INCOME_ROOT->value,
        'code' => '70000',
        'name' => 'Pendapatan Lain-lain',
        'account_type' => 'income',
        'normal_balance' => 'credit',
        'is_group' => true,
        'children' => [],
    ],
    'other_expense_root' => [
        'system_key' => ChartOfAccountSystemKeyEnum::OTHER_EXPENSE_ROOT->value,
        'code' => '80000',
        'name' => 'Beban Lain-lain',
        'account_type' => 'expense',
        'normal_balance' => 'debit',
        'is_group' => true,
        'children' => [],
    ],
];
