<?php

use App\Enums\ChartOfAccountSystemKeyEnum;

return [
    'asset_root' => [
        'system_key' => ChartOfAccountSystemKeyEnum::ASSET_ROOT->value,
        'code' => '01',
        'name' => 'Aset',
        'account_type' => 'asset',
        'normal_balance' => 'debit',
        'is_group' => true,
        'children' => [
            'current_asset' => [
                'system_key' => ChartOfAccountSystemKeyEnum::ASSET_CURRENT->value,
                'code' => '01.01',
                'name' => 'Aset Lancar',
                'account_type' => 'asset',
                'normal_balance' => 'debit',
                'is_group' => true,
                'children' => [
                    'cash_and_cash_equivalents' => [
                        'system_key' => ChartOfAccountSystemKeyEnum::ASSET_CURRENT_CASH_AND_CASH_EQUIVALENTS->value,
                        'code' => '01.01.01',
                        'name' => 'Kas dan Setara Kas',
                        'account_type' => 'asset',
                        'normal_balance' => 'debit',
                        'is_group' => true,
                        'children' => [
                            'cash' => [
                                'system_key' => ChartOfAccountSystemKeyEnum::ASSET_CURRENT_CASH->value,
                                'code' => '01.01.01.01',
                                'name' => 'Kas',
                                'account_type' => 'asset',
                                'normal_balance' => 'debit',
                                'is_group' => true,
                                'children' => [],
                            ],
                            'bank' => [
                                'system_key' => ChartOfAccountSystemKeyEnum::ASSET_CURRENT_BANK->value,
                                'code' => '01.01.01.02',
                                'name' => 'Bank',
                                'account_type' => 'asset',
                                'normal_balance' => 'debit',
                                'is_group' => true,
                                'children' => [],
                            ],
                        ],
                    ],
                    'account_receivable' => [
                        'system_key' => ChartOfAccountSystemKeyEnum::ASSET_CURRENT_ACCOUNT_RECEIVABLE->value,
                        'code' => '01.01.02',
                        'name' => 'Piutang Usaha',
                        'account_type' => 'asset',
                        'normal_balance' => 'debit',
                        'is_group' => false,
                    ],
                    'inventory' => [
                        'system_key' => ChartOfAccountSystemKeyEnum::ASSET_CURRENT_INVENTORY->value,
                        'code' => '01.01.03',
                        'name' => 'Persediaan',
                        'account_type' => 'asset',
                        'normal_balance' => 'debit',
                        'is_group' => false,
                    ],
                    'prepaid_expense' => [
                        'system_key' => ChartOfAccountSystemKeyEnum::ASSET_CURRENT_PREPAID_EXPENSE->value,
                        'code' => '01.01.04',
                        'name' => 'Biaya Dibayar Dimuka',
                        'account_type' => 'asset',
                        'normal_balance' => 'debit',
                        'is_group' => false,
                    ],
                ],
            ],
            'non_current_asset' => [
                'system_key' => ChartOfAccountSystemKeyEnum::ASSET_NON_CURRENT->value,
                'code' => '01.02',
                'name' => 'Aset Tidak Lancar',
                'account_type' => 'asset',
                'normal_balance' => 'debit',
                'is_group' => true,
                'children' => [
                    'fixed_asset' => [
                        'system_key' => ChartOfAccountSystemKeyEnum::ASSET_NON_CURRENT_FIXED_ASSET->value,
                        'code' => '01.02.01',
                        'name' => 'Aset Tetap',
                        'account_type' => 'asset',
                        'normal_balance' => 'debit',
                        'is_group' => false,
                    ],
                    'accumulated_depreciation' => [
                        'system_key' => ChartOfAccountSystemKeyEnum::ASSET_NON_CURRENT_ACCUMULATED_DEPRECIATION->value,
                        'code' => '01.02.02',
                        'name' => 'Akumulasi Penyusutan',
                        'account_type' => 'asset',
                        'normal_balance' => 'credit',
                        'is_group' => false,
                    ],
                    'intangible_asset' => [
                        'system_key' => ChartOfAccountSystemKeyEnum::ASSET_NON_CURRENT_INTANGIBLE_ASSET->value,
                        'code' => '01.02.03',
                        'name' => 'Aset Tidak Berwujud',
                        'account_type' => 'asset',
                        'normal_balance' => 'debit',
                        'is_group' => false,
                    ],
                ],
            ],
        ],
    ],
    'liability_root' => [
        'system_key' => ChartOfAccountSystemKeyEnum::LIABILITY_ROOT->value,
        'code' => '02',
        'name' => 'Liabilitas',
        'account_type' => 'liability',
        'normal_balance' => 'credit',
        'is_group' => true,
        'children' => [
            'account_payable' => [
                'system_key' => ChartOfAccountSystemKeyEnum::LIABILITY_ACCOUNT_PAYABLE->value,
                'code' => '02.01',
                'name' => 'Utang Usaha',
                'account_type' => 'liability',
                'normal_balance' => 'credit',
                'is_group' => true,
            ],
            'tax_payable' => [
                'system_key' => ChartOfAccountSystemKeyEnum::LIABILITY_TAX_PAYABLE->value,
                'code' => '02.02',
                'name' => 'Utang Pajak',
                'account_type' => 'liability',
                'normal_balance' => 'credit',
                'is_group' => false,
            ],
        ],
    ],
    'equity_root' => [
        'system_key' => ChartOfAccountSystemKeyEnum::EQUITY_ROOT->value,
        'code' => '03',
        'name' => 'Ekuitas',
        'account_type' => 'equity',
        'normal_balance' => 'credit',
        'is_group' => true,
        'children' => [
            'capital' => [
                'system_key' => ChartOfAccountSystemKeyEnum::EQUITY_CAPITAL->value,
                'code' => '03.01',
                'name' => 'Modal',
                'account_type' => 'equity',
                'normal_balance' => 'credit',
                'is_group' => true,
                'children' => [
                    'opening_capital' => [
                        'system_key' => ChartOfAccountSystemKeyEnum::EQUITY_CAPITAL_OPENING_CAPITAL->value,
                        'code' => '03.01.01',
                        'name' => 'Modal Awal',
                        'account_type' => 'equity',
                        'normal_balance' => 'credit',
                        'is_group' => false,
                    ],
                    'additional_capital' => [
                        'system_key' => ChartOfAccountSystemKeyEnum::EQUITY_CAPITAL_ADDITIONAL_CAPITAL->value,
                        'code' => '03.01.02',
                        'name' => 'Modal Tambahan',
                        'account_type' => 'equity',
                        'normal_balance' => 'credit',
                        'is_group' => false,
                    ],
                    'drawing' => [
                        'system_key' => ChartOfAccountSystemKeyEnum::EQUITY_CAPITAL_DRAWING->value,
                        'code' => '03.01.03',
                        'name' => 'Prive/Penarikan Modal',
                        'account_type' => 'equity',
                        'normal_balance' => 'debit',
                        'is_group' => false,
                    ],
                ],
            ],
            'current_month_earnings' => [
                'system_key' => ChartOfAccountSystemKeyEnum::EQUITY_CURRENT_MONTH_EARNINGS->value,
                'code' => '03.02',
                'name' => 'Laba Bulan Berjalan',
                'account_type' => 'equity',
                'normal_balance' => 'credit',
                'is_group' => false,
            ],
            'current_year_earnings' => [
                'system_key' => ChartOfAccountSystemKeyEnum::EQUITY_CURRENT_YEAR_EARNINGS->value,
                'code' => '03.03',
                'name' => 'Laba Tahun Berjalan',
                'account_type' => 'equity',
                'normal_balance' => 'credit',
                'is_group' => false,
            ],
            'retained_earnings' => [
                'system_key' => ChartOfAccountSystemKeyEnum::EQUITY_RETAINED_EARNINGS->value,
                'code' => '03.04',
                'name' => 'Laba Ditahan',
                'account_type' => 'equity',
                'normal_balance' => 'credit',
                'is_group' => false,
            ],
        ],
    ],
    'income_root' => [
        'system_key' => ChartOfAccountSystemKeyEnum::INCOME_ROOT->value,
        'code' => '04',
        'name' => 'Pendapatan',
        'account_type' => 'income',
        'normal_balance' => 'credit',
        'is_group' => true,
        'children' => [
            'sales_income' => [
                'system_key' => ChartOfAccountSystemKeyEnum::INCOME_SALES->value,
                'code' => '04.01',
                'name' => 'Pendapatan Penjualan',
                'account_type' => 'income',
                'normal_balance' => 'credit',
                'is_group' => false,
            ],
            'service_income' => [
                'system_key' => ChartOfAccountSystemKeyEnum::INCOME_SERVICE->value,
                'code' => '04.02',
                'name' => 'Pendapatan Jasa',
                'account_type' => 'income',
                'normal_balance' => 'credit',
                'is_group' => false,
            ],
        ],
    ],
    'cogs_root' => [
        'system_key' => ChartOfAccountSystemKeyEnum::COGS_ROOT->value,
        'code' => '05',
        'name' => 'Harga Pokok Penjualan',
        'account_type' => 'expense',
        'normal_balance' => 'debit',
        'is_group' => true,
        'children' => [
            'material_cost' => [
                'system_key' => ChartOfAccountSystemKeyEnum::COGS_MATERIAL_COST->value,
                'code' => '05.01',
                'name' => 'Beban Bahan Baku',
                'account_type' => 'expense',
                'normal_balance' => 'debit',
                'is_group' => false,
            ],
            'direct_labor_cost' => [
                'system_key' => ChartOfAccountSystemKeyEnum::COGS_DIRECT_LABOR_COST->value,
                'code' => '05.02',
                'name' => 'Beban Tenaga Kerja Langsung',
                'account_type' => 'expense',
                'normal_balance' => 'debit',
                'is_group' => false,
            ],
        ],
    ],
    'expense_root' => [
        'system_key' => ChartOfAccountSystemKeyEnum::EXPENSE_ROOT->value,
        'code' => '06',
        'name' => 'Beban Operasional',
        'account_type' => 'expense',
        'normal_balance' => 'debit',
        'is_group' => true,
        'children' => [],
    ],
    'other_income_root' => [
        'system_key' => ChartOfAccountSystemKeyEnum::OTHER_INCOME_ROOT->value,
        'code' => '07',
        'name' => 'Pendapatan Lain-lain',
        'account_type' => 'income',
        'normal_balance' => 'credit',
        'is_group' => true,
        'children' => [],
    ],
    'other_expense_root' => [
        'system_key' => ChartOfAccountSystemKeyEnum::OTHER_EXPENSE_ROOT->value,
        'code' => '08',
        'name' => 'Beban Lain-lain',
        'account_type' => 'expense',
        'normal_balance' => 'debit',
        'is_group' => true,
        'children' => [],
    ],
];
